terraform {
  required_version = ">= 1.5.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
  }

  backend "local" {
    path = "terraform.tfstate"
  }
}

provider "aws" {
  region = var.aws_region
}

data "aws_vpc" "default" {
  count   = var.vpc_id == null ? 1 : 0
  default = true
}

data "aws_subnets" "default" {
  count = length(var.subnet_ids) == 0 ? 1 : 0
  filter {
    name   = "vpc-id"
    values = [local.vpc_id]
  }
}

data "aws_route53_zone" "selected" {
  count        = var.route53_zone_name != null && var.route53_record_name != null ? 1 : 0
  name         = "${trimsuffix(var.route53_zone_name, ".")}."
  private_zone = false
}

locals {
  vpc_id              = var.vpc_id != null ? var.vpc_id : data.aws_vpc.default[0].id
  selected_subnet_ids = length(var.subnet_ids) > 0 ? var.subnet_ids : data.aws_subnets.default[0].ids
  tls_secret_arns     = toset(compact([var.tls_certificate_secret_arn, var.tls_private_key_secret_arn]))
  tls_secret_env = merge(
    var.tls_certificate_secret_arn != null ? { TLS_CERT_PEM = var.tls_certificate_secret_arn } : {},
    var.tls_private_key_secret_arn != null ? { TLS_KEY_PEM = var.tls_private_key_secret_arn } : {}
  )
}

resource "aws_lb" "this" {
  name               = "${var.service_name}-nlb"
  internal           = false
  load_balancer_type = "network"
  subnets            = local.selected_subnet_ids
}

resource "aws_lb_target_group" "this" {
  name        = "${var.service_name}-tg"
  port        = var.game_port
  protocol    = "TCP"
  vpc_id      = local.vpc_id
  target_type = "ip"
}

resource "aws_lb_listener" "tcp" {
  load_balancer_arn = aws_lb.this.arn
  port              = var.game_port
  protocol          = "TCP"

  default_action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.this.arn
  }
}

module "service" {
  source = "../../modules/ecs-public-service"

  github_username     = var.github_username
  github_repo_name    = var.github_repo_name
  ghcr_pat_secret_arn = var.ghcr_pat_secret_arn

  aws_region       = var.aws_region
  service_name     = var.service_name
  vpc_id           = local.vpc_id
  subnet_ids       = local.selected_subnet_ids
  container_port   = var.game_port
  image_tag        = var.image_tag
  image_repo       = var.image_repo
  cpu              = var.cpu
  memory           = var.memory
  assign_public_ip = var.assign_public_ip
  desired_count    = var.desired_count
  target_group_arn = aws_lb_target_group.this.arn
  task_secret_arns = local.tls_secret_arns

  environment = {
    GAME_SERVER_PORT = tostring(var.game_port)
  }

  secrets = local.tls_secret_env
}

resource "aws_route53_record" "server" {
  count   = var.route53_zone_name != null && var.route53_record_name != null ? 1 : 0
  zone_id = data.aws_route53_zone.selected[0].zone_id
  name    = var.route53_record_name
  type    = "A"

  alias {
    name                   = aws_lb.this.dns_name
    zone_id                = aws_lb.this.zone_id
    evaluate_target_health = true
  }
}

locals {
  game_server_host_for_client = length(aws_route53_record.server) > 0 ? trimsuffix(aws_route53_record.server[0].fqdn, ".") : aws_lb.this.dns_name
}

resource "local_file" "client_env" {
  count    = var.write_client_env_file ? 1 : 0
  filename = "${path.module}/../../../client/env/.env"
  content  = <<-EOT
    # Generated by Terraform from infra/services/server. Manual edits may be overwritten.
    USE_AWS_SERVICES=true
    AWS_REGION=${var.aws_region}

    # Game Server
    DOCKER_GAME_SERVER_HOST=127.0.0.1
    DOCKER_GAME_SERVER_PORT=${var.game_port}
    AWS_GAME_SERVER_HOST=${local.game_server_host_for_client}
    AWS_GAME_SERVER_PORT=${var.game_port}

    # Backward compatibility key used in older local env files
    AWS_GAME_SERVER_SERVICE_HOST=${local.game_server_host_for_client}
    AWS_GAME_SERVER_SERVICE_PORT=${var.game_port}
  EOT
}
