# ---------- Build Stage ----------
FROM gcc:13-bookworm AS builder
WORKDIR /app
COPY . .
RUN apt-get update && apt-get install -y make && rm -rf /var/lib/apt/lists/*
RUN make

# ---------- Runtime Stage ----------
FROM gcc:13-bookworm AS runtime
WORKDIR /app
COPY --from=builder /app/server .
EXPOSE 4000
CMD ["./server"]
