version: "3.9"

services:
  game-server:
    build: .
    container_name: speedcardgame-server
    ports:
      - "4000:4000"
    restart: unless-stopped
    environment:
      - GAME_SERVER_PORT=4000
      - TLS_CERT_PATH=/certs/server.crt
      - TLS_KEY_PATH=/certs/server.key
    sysctls:
      - net.core.somaxconn=65535
    volumes:
      - ./certs:/certs:ro