
name: Build and Push Docker to GHCR

on:
  push:
    branches:
      - main
    workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    strategy:
      matrix:
        service: [auth, cards, server]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push ${{ matrix.service }} Service
        run: |
          docker build -f backend/api/${{ matrix.service }}/Dockerfile -t ghcr.io/${{ github.repository_owner }}/g4t2-${{ matrix.service }}-service:latest backend/api/${{ matrix.service }}/
          docker push ghcr.io/${{ github.repository_owner }}/g4t2-${{ matrix.service }}-service:latest
